<a href="https://colab.research.google.com/github/JavierHerreraPadilla/powerbi_sierracol/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy es la librería principal que tiene Python para realizar álgebra lineal

NumPy (Numerical Python) es una biblioteca fundamental en el ecosistema de Python utilizada para realizar operaciones numéricas y matemáticas en arreglos multidimensionales. Proporciona una estructura de datos eficiente llamada "ndarray" (arreglo multidimensional) que permite almacenar y manipular grandes conjuntos de datos de manera rápida y eficiente.

Algunas características clave de NumPy incluyen:

Arreglos multidimensionales: NumPy permite crear y manipular arreglos de varias dimensiones, como vectores, matrices y tensores, lo que facilita el procesamiento de datos en varias dimensiones.

Funciones matemáticas: Ofrece una amplia gama de funciones matemáticas y operaciones de álgebra lineal, como sumas, productos, transposiciones, descomposiciones y más. Estas operaciones se optimizan para un rendimiento eficiente en términos de velocidad y memoria.

Broadcasting: NumPy introduce broadcasting, que permite operar en arreglos de diferentes formas y tamaños sin necesidad de duplicar los datos. Esto simplifica la escritura de código y mejora la eficiencia.

Indexación avanzada: Proporciona herramientas para acceder y manipular elementos específicos dentro de los arreglos utilizando índices y segmentación avanzada.

Integración con otras bibliotecas: NumPy se utiliza ampliamente en el ámbito científico y de la ingeniería como base para otras bibliotecas, como SciPy, pandas y scikit-learn, para realizar análisis de datos, cálculos científicos y aprendizaje automático.


**NUMPY ARRAY

In [ ]:
# VECTORES (ARRAY) DE 1 DIMENSIÓN o MATRICES (2 DIMENSIONES)

In [ ]:
mi_lista = [1, 2, 3]
mi_lista

[1, 2, 3]

In [ ]:
import numpy as np
import sys

In [ ]:
arr = np.array(mi_lista)
arr

array([1, 2, 3])

In [ ]:
# LISTA DE LISTA ARA CREAR UNA MATRIZ
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np_mat = np.array(my_mat)
np_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# GENERACIÓN DE ARRAYS DESDE np
np.arange(0,10+1)
#np.arange(inicio, fin, paso)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,10+1, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# array de ceros
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# matriz de ceros
np.zeros((2,3))
# 2 filas, 3 columnas

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# array de unos
np.ones(3)

array([1., 1., 1.])

In [ ]:
# matriz de unos
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# linspace - es una función en NumPy que crea un arreglo con valores equidistantes en un rango dado
np.linspace(0, 5, 10)
# np.linspace(inicio, fin, puntos) - no confundir con np.arange

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
# matriz identidad - matriz cuya diagonal es 1.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# arreglos de números aleatorios -
# random.rand es una función en NumPy que genera números aleatorios en un arreglo con distribución uniforme en el intervalo [0, 1)
np.random.rand(3)

array([0.93279464, 0.12055591, 0.5951712 ])

In [ ]:
#matriz
np.random.rand(2,3)

array([[0.92193885, 0.37932988, 0.24894408],
       [0.54853776, 0.51183512, 0.56518506]])

In [ ]:
#np.random.randn() es una función en NumPy que genera números aleatorios distribuidos según una
#distribución normal estándar (media 0 y desviación estándar 1) en un arreglo.
np.random.randn(2)

array([ 0.93308757, -0.0056798 ])

In [ ]:
# matriz
np.random.randn(2,2)

array([[-0.36679094, -0.23984466],
       [-0.15200365,  0.52106082]])

In [ ]:
#np.random.randint(1, 100) genera un número entero aleatorio en el rango [1, 100).
np.random.randint(1,100)

41

In [ ]:
# 10 enteros aleátorios
np.random.randint(1,100,10)

array([10, 38, 77, 76, 12, 64, 27, 19, 20, 34])

#Métodos de arrays

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([ 4, 38, 34, 46, 18,  1, 32, 32, 27, 49])

In [ ]:
#RESHAPE reshape es un método en NumPy que se utiliza para cambiar la forma (dimensiones)
#de un arreglo multidimensional sin cambiar los datos contenidos en él
arr.reshape(5, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(5, 4)
# cannot reshape array of size 25 into shape (5,4)

ValueError: ignored

In [ ]:
ranarr

array([ 4, 38, 34, 46, 18,  1, 32, 32, 27, 49])

In [ ]:
print("el máximo de ranarr es", ranarr.max())
print("el mínimo de ranarr", ranarr.max())

el máximo de ranarr es 49
el mínimo de ranarr 49


In [ ]:
print("el máximo de ranarr está en el índice", ranarr.argmax())
print("el máximo de ranarr está en el índice", ranarr.argmin())

el máximo de ranarr está en el índice 9
el máximo de ranarr está en el índice 5


In [ ]:
# forma de un array
arr.shape

(25,)

In [ ]:
arr.reshape(5, 5).shape

(5, 5)

#ÍNDICES Y SELECCIÓN EN NP

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# seleccionar un valor
arr[0]

0

In [ ]:
#slicing
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# BROADCASTING - diferencia entre listas y array
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# INDEXAR EN UNA MATRIZ

In [ ]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# hay 2 formatos para indexar matrices
#Formato doble corchete
arr_2d[0][1]
#fila cero, columna 1

10

In [ ]:
#Fila
arr_2d[1]

array([20, 25, 30])

In [ ]:
# formato corchete coma
arr_2d[1, 2]

30

In [ ]:
#submatrices - slice
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

#Selección condicional

In [ ]:
arr = np.arange(0, 11)

In [ ]:
# cuáles elementos del array son mayores a 5
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
# Pasar el condicional al array original devuelve solo los valores que cumplen
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
#seleccionar los valores del array que son menor igual a 3
arr[arr <= 3]

array([0, 1, 2, 3])

In [ ]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#Operaciones con numpy

In [ ]:
# array - array, array -escalar
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# arr - arr
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr / arr

<ipython-input-121-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# arr - escalar
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
1 / arr

<ipython-input-125-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
# FUNCIONES UNIVERSALES
#raiz cuadrada
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])